// Mocks generated by Mockito 5.4.5 from annotations
// in dart_libp2p_kad_dht/test/record/ipns_validator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i7;

import 'package:dcid/dcid.dart' as _i2;
import 'package:dart_libp2p/core/crypto/keys.dart' as _i9;
import 'package:dart_libp2p/core/crypto/pb/crypto.pb.dart' as _i3;
import 'package:dart_libp2p/core/multiaddr.dart' as _i11;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i5;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i6;
import 'package:dart_libp2p/core/peerstore.dart' as _i4;
import 'package:dart_libp2p/p2p/discovery/peer_info.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCID_0 extends _i1.SmartFake implements _i2.CID {
  _FakeCID_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyType_1 extends _i1.SmartFake implements _i3.KeyType {
  _FakeKeyType_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddrBook_2 extends _i1.SmartFake implements _i4.AddrBook {
  _FakeAddrBook_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyBook_3 extends _i1.SmartFake implements _i4.KeyBook {
  _FakeKeyBook_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerMetadata_4 extends _i1.SmartFake implements _i4.PeerMetadata {
  _FakePeerMetadata_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetrics_5 extends _i1.SmartFake implements _i4.Metrics {
  _FakeMetrics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtoBook_6 extends _i1.SmartFake implements _i4.ProtoBook {
  _FakeProtoBook_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddrInfo_7 extends _i1.SmartFake implements _i5.AddrInfo {
  _FakeAddrInfo_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PeerId].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerId extends _i1.Mock implements _i6.PeerId {
  MockPeerId() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CID toCid() => (super.noSuchMethod(
        Invocation.method(
          #toCid,
          [],
        ),
        returnValue: _FakeCID_0(
          this,
          Invocation.method(
            #toCid,
            [],
          ),
        ),
      ) as _i2.CID);

  @override
  _i7.Uint8List toBytes() => (super.noSuchMethod(
        Invocation.method(
          #toBytes,
          [],
        ),
        returnValue: _i7.Uint8List(0),
      ) as _i7.Uint8List);

  @override
  String toCIDString() => (super.noSuchMethod(
        Invocation.method(
          #toCIDString,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toCIDString,
            [],
          ),
        ),
      ) as String);

  @override
  String toBase58() => (super.noSuchMethod(
        Invocation.method(
          #toBase58,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #toBase58,
            [],
          ),
        ),
      ) as String);

  @override
  String shortString() => (super.noSuchMethod(
        Invocation.method(
          #shortString,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #shortString,
            [],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> loggable() => (super.noSuchMethod(
        Invocation.method(
          #loggable,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool matchesPublicKey(_i9.PublicKey? publicKey) => (super.noSuchMethod(
        Invocation.method(
          #matchesPublicKey,
          [publicKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool matchesPrivateKey(_i9.PrivateKey? privateKey) => (super.noSuchMethod(
        Invocation.method(
          #matchesPrivateKey,
          [privateKey],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<_i9.PublicKey?> extractPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #extractPublicKey,
          [],
        ),
        returnValue: _i10.Future<_i9.PublicKey?>.value(),
      ) as _i10.Future<_i9.PublicKey?>);

  @override
  bool isValid() => (super.noSuchMethod(
        Invocation.method(
          #isValid,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [PublicKey].
///
/// See the documentation for Mockito's code generation for more information.
class MockPublicKey extends _i1.Mock implements _i9.PublicKey {
  MockPublicKey() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.KeyType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _FakeKeyType_1(
          this,
          Invocation.getter(#type),
        ),
      ) as _i3.KeyType);

  @override
  _i7.Uint8List get raw => (super.noSuchMethod(
        Invocation.getter(#raw),
        returnValue: _i7.Uint8List(0),
      ) as _i7.Uint8List);

  @override
  _i10.Future<bool> verify(
    _i7.Uint8List? data,
    _i7.Uint8List? signature,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [
            data,
            signature,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> equals(_i9.PublicKey? other) => (super.noSuchMethod(
        Invocation.method(
          #equals,
          [other],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i7.Uint8List marshal() => (super.noSuchMethod(
        Invocation.method(
          #marshal,
          [],
        ),
        returnValue: _i7.Uint8List(0),
      ) as _i7.Uint8List);
}

/// A class which mocks [Peerstore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerstore extends _i1.Mock implements _i4.Peerstore {
  MockPeerstore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AddrBook get addrBook => (super.noSuchMethod(
        Invocation.getter(#addrBook),
        returnValue: _FakeAddrBook_2(
          this,
          Invocation.getter(#addrBook),
        ),
      ) as _i4.AddrBook);

  @override
  _i4.KeyBook get keyBook => (super.noSuchMethod(
        Invocation.getter(#keyBook),
        returnValue: _FakeKeyBook_3(
          this,
          Invocation.getter(#keyBook),
        ),
      ) as _i4.KeyBook);

  @override
  _i4.PeerMetadata get peerMetadata => (super.noSuchMethod(
        Invocation.getter(#peerMetadata),
        returnValue: _FakePeerMetadata_4(
          this,
          Invocation.getter(#peerMetadata),
        ),
      ) as _i4.PeerMetadata);

  @override
  _i4.Metrics get metrics => (super.noSuchMethod(
        Invocation.getter(#metrics),
        returnValue: _FakeMetrics_5(
          this,
          Invocation.getter(#metrics),
        ),
      ) as _i4.Metrics);

  @override
  _i4.ProtoBook get protoBook => (super.noSuchMethod(
        Invocation.getter(#protoBook),
        returnValue: _FakeProtoBook_6(
          this,
          Invocation.getter(#protoBook),
        ),
      ) as _i4.ProtoBook);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i5.AddrInfo> peerInfo(_i6.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #peerInfo,
          [id],
        ),
        returnValue: _i10.Future<_i5.AddrInfo>.value(_FakeAddrInfo_7(
          this,
          Invocation.method(
            #peerInfo,
            [id],
          ),
        )),
      ) as _i10.Future<_i5.AddrInfo>);

  @override
  _i10.Future<List<_i6.PeerId>> peers() => (super.noSuchMethod(
        Invocation.method(
          #peers,
          [],
        ),
        returnValue: _i10.Future<List<_i6.PeerId>>.value(<_i6.PeerId>[]),
      ) as _i10.Future<List<_i6.PeerId>>);

  @override
  _i10.Future<void> removePeer(_i6.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #removePeer,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addOrUpdatePeer(
    _i6.PeerId? peerId, {
    List<_i11.MultiAddr>? addrs,
    List<String>? protocols,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdatePeer,
          [peerId],
          {
            #addrs: addrs,
            #protocols: protocols,
            #metadata: metadata,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i12.PeerInfo?> getPeer(_i6.PeerId? peerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeer,
          [peerId],
        ),
        returnValue: _i10.Future<_i12.PeerInfo?>.value(),
      ) as _i10.Future<_i12.PeerInfo?>);
}

/// A class which mocks [KeyBook].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyBook extends _i1.Mock implements _i4.KeyBook {
  MockKeyBook() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i9.PublicKey?> pubKey(_i6.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #pubKey,
          [id],
        ),
        returnValue: _i10.Future<_i9.PublicKey?>.value(),
      ) as _i10.Future<_i9.PublicKey?>);

  @override
  void addPubKey(
    _i6.PeerId? id,
    _i9.PublicKey? pk,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addPubKey,
          [
            id,
            pk,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i9.PrivateKey?> privKey(_i6.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #privKey,
          [id],
        ),
        returnValue: _i10.Future<_i9.PrivateKey?>.value(),
      ) as _i10.Future<_i9.PrivateKey?>);

  @override
  void addPrivKey(
    _i6.PeerId? id,
    _i9.PrivateKey? sk,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addPrivKey,
          [
            id,
            sk,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<List<_i6.PeerId>> peersWithKeys() => (super.noSuchMethod(
        Invocation.method(
          #peersWithKeys,
          [],
        ),
        returnValue: _i10.Future<List<_i6.PeerId>>.value(<_i6.PeerId>[]),
      ) as _i10.Future<List<_i6.PeerId>>);

  @override
  void removePeer(_i6.PeerId? id) => super.noSuchMethod(
        Invocation.method(
          #removePeer,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
