// Mocks generated by Mockito 5.4.5 from annotations
// in dart_libp2p_kad_dht/test/dht/dht_retry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:typed_data' as _i16;

import 'package:dcid/dcid.dart' as _i19;
import 'package:dart_libp2p/core/connmgr/conn_manager.dart' as _i6;
import 'package:dart_libp2p/core/event/bus.dart' as _i7;
import 'package:dart_libp2p/core/host/host.dart' as _i12;
import 'package:dart_libp2p/core/multiaddr.dart' as _i13;
import 'package:dart_libp2p/core/network/conn.dart' as _i9;
import 'package:dart_libp2p/core/network/context.dart' as _i15;
import 'package:dart_libp2p/core/network/network.dart' as _i4;
import 'package:dart_libp2p/core/network/rcmgr.dart' as _i10;
import 'package:dart_libp2p/core/network/stream.dart' as _i8;
import 'package:dart_libp2p/core/peer/addr_info.dart' as _i11;
import 'package:dart_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:dart_libp2p/core/peerstore.dart' as _i3;
import 'package:dart_libp2p/core/protocol/switch.dart' as _i5;
import 'package:dart_libp2p/p2p/discovery/peer_info.dart' as _i20;
import 'package:dart_libp2p_kad_dht/src/providers/provider_store.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerstore_1 extends _i1.SmartFake implements _i3.Peerstore {
  _FakePeerstore_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetwork_2 extends _i1.SmartFake implements _i4.Network {
  _FakeNetwork_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtocolSwitch_3 extends _i1.SmartFake
    implements _i5.ProtocolSwitch {
  _FakeProtocolSwitch_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnManager_4 extends _i1.SmartFake implements _i6.ConnManager {
  _FakeConnManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventBus_5 extends _i1.SmartFake implements _i7.EventBus {
  _FakeEventBus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i8.P2PStream<T> {
  _FakeP2PStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConn_7 extends _i1.SmartFake implements _i9.Conn {
  _FakeConn_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamStats_8 extends _i1.SmartFake implements _i8.StreamStats {
  _FakeStreamStats_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManagementScope_9 extends _i1.SmartFake
    implements _i10.StreamManagementScope {
  _FakeStreamManagementScope_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddrBook_10 extends _i1.SmartFake implements _i3.AddrBook {
  _FakeAddrBook_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyBook_11 extends _i1.SmartFake implements _i3.KeyBook {
  _FakeKeyBook_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerMetadata_12 extends _i1.SmartFake implements _i3.PeerMetadata {
  _FakePeerMetadata_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMetrics_13 extends _i1.SmartFake implements _i3.Metrics {
  _FakeMetrics_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProtoBook_14 extends _i1.SmartFake implements _i3.ProtoBook {
  _FakeProtoBook_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddrInfo_15 extends _i1.SmartFake implements _i11.AddrInfo {
  _FakeAddrInfo_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSubscription_16<T> extends _i1.SmartFake
    implements _i7.Subscription<T> {
  _FakeSubscription_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmitter_17 extends _i1.SmartFake implements _i7.Emitter {
  _FakeEmitter_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Host].
///
/// See the documentation for Mockito's code generation for more information.
class MockHost extends _i1.Mock implements _i12.Host {
  MockHost() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PeerId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.PeerId);

  @override
  _i3.Peerstore get peerStore => (super.noSuchMethod(
        Invocation.getter(#peerStore),
        returnValue: _FakePeerstore_1(
          this,
          Invocation.getter(#peerStore),
        ),
      ) as _i3.Peerstore);

  @override
  List<_i13.MultiAddr> get addrs => (super.noSuchMethod(
        Invocation.getter(#addrs),
        returnValue: <_i13.MultiAddr>[],
      ) as List<_i13.MultiAddr>);

  @override
  _i4.Network get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetwork_2(
          this,
          Invocation.getter(#network),
        ),
      ) as _i4.Network);

  @override
  _i5.ProtocolSwitch get mux => (super.noSuchMethod(
        Invocation.getter(#mux),
        returnValue: _FakeProtocolSwitch_3(
          this,
          Invocation.getter(#mux),
        ),
      ) as _i5.ProtocolSwitch);

  @override
  _i6.ConnManager get connManager => (super.noSuchMethod(
        Invocation.getter(#connManager),
        returnValue: _FakeConnManager_4(
          this,
          Invocation.getter(#connManager),
        ),
      ) as _i6.ConnManager);

  @override
  _i7.EventBus get eventBus => (super.noSuchMethod(
        Invocation.getter(#eventBus),
        returnValue: _FakeEventBus_5(
          this,
          Invocation.getter(#eventBus),
        ),
      ) as _i7.EventBus);

  @override
  _i14.Future<void> connect(
    _i11.AddrInfo? pi, {
    _i15.Context? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [pi],
          {#context: context},
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void setStreamHandler(
    String? pid,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandler,
          [
            pid,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setStreamHandlerMatch(
    String? pid,
    bool Function(String)? match,
    _i4.StreamHandler? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setStreamHandlerMatch,
          [
            pid,
            match,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeStreamHandler(String? pid) => super.noSuchMethod(
        Invocation.method(
          #removeStreamHandler,
          [pid],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<_i8.P2PStream<dynamic>> newStream(
    _i2.PeerId? p,
    List<String>? pids,
    _i15.Context? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [
            p,
            pids,
            context,
          ],
        ),
        returnValue:
            _i14.Future<_i8.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [
              p,
              pids,
              context,
            ],
          ),
        )),
      ) as _i14.Future<_i8.P2PStream<dynamic>>);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [P2PStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockP2PStream<T> extends _i1.Mock implements _i8.P2PStream<T> {
  MockP2PStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Conn get conn => (super.noSuchMethod(
        Invocation.getter(#conn),
        returnValue: _FakeConn_7(
          this,
          Invocation.getter(#conn),
        ),
      ) as _i9.Conn);

  @override
  _i8.P2PStream<_i16.Uint8List> get incoming => (super.noSuchMethod(
        Invocation.getter(#incoming),
        returnValue: _FakeP2PStream_6<_i16.Uint8List>(
          this,
          Invocation.getter(#incoming),
        ),
      ) as _i8.P2PStream<_i16.Uint8List>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  String id() => (super.noSuchMethod(
        Invocation.method(
          #id,
          [],
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #id,
            [],
          ),
        ),
      ) as String);

  @override
  String protocol() => (super.noSuchMethod(
        Invocation.method(
          #protocol,
          [],
        ),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.method(
            #protocol,
            [],
          ),
        ),
      ) as String);

  @override
  _i14.Future<void> setProtocol(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setProtocol,
          [id],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i8.StreamStats stat() => (super.noSuchMethod(
        Invocation.method(
          #stat,
          [],
        ),
        returnValue: _FakeStreamStats_8(
          this,
          Invocation.method(
            #stat,
            [],
          ),
        ),
      ) as _i8.StreamStats);

  @override
  _i10.StreamManagementScope scope() => (super.noSuchMethod(
        Invocation.method(
          #scope,
          [],
        ),
        returnValue: _FakeStreamManagementScope_9(
          this,
          Invocation.method(
            #scope,
            [],
          ),
        ),
      ) as _i10.StreamManagementScope);

  @override
  _i14.Future<_i16.Uint8List> read([int? maxLength]) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [maxLength],
        ),
        returnValue: _i14.Future<_i16.Uint8List>.value(_i16.Uint8List(0)),
      ) as _i14.Future<_i16.Uint8List>);

  @override
  _i14.Future<void> write(_i16.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> closeWrite() => (super.noSuchMethod(
        Invocation.method(
          #closeWrite,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> closeRead() => (super.noSuchMethod(
        Invocation.method(
          #closeRead,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> setDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setDeadline,
          [time],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> setReadDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setReadDeadline,
          [time],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> setWriteDeadline(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #setWriteDeadline,
          [time],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [ProviderStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderStore extends _i1.Mock implements _i18.ProviderStore {
  MockProviderStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<void> addProvider(
    _i19.CID? key,
    _i11.AddrInfo? provider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProvider,
          [
            key,
            provider,
          ],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<List<_i11.AddrInfo>> getProviders(_i19.CID? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProviders,
          [key],
        ),
        returnValue: _i14.Future<List<_i11.AddrInfo>>.value(<_i11.AddrInfo>[]),
      ) as _i14.Future<List<_i11.AddrInfo>>);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}

/// A class which mocks [Peerstore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeerstore extends _i1.Mock implements _i3.Peerstore {
  MockPeerstore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AddrBook get addrBook => (super.noSuchMethod(
        Invocation.getter(#addrBook),
        returnValue: _FakeAddrBook_10(
          this,
          Invocation.getter(#addrBook),
        ),
      ) as _i3.AddrBook);

  @override
  _i3.KeyBook get keyBook => (super.noSuchMethod(
        Invocation.getter(#keyBook),
        returnValue: _FakeKeyBook_11(
          this,
          Invocation.getter(#keyBook),
        ),
      ) as _i3.KeyBook);

  @override
  _i3.PeerMetadata get peerMetadata => (super.noSuchMethod(
        Invocation.getter(#peerMetadata),
        returnValue: _FakePeerMetadata_12(
          this,
          Invocation.getter(#peerMetadata),
        ),
      ) as _i3.PeerMetadata);

  @override
  _i3.Metrics get metrics => (super.noSuchMethod(
        Invocation.getter(#metrics),
        returnValue: _FakeMetrics_13(
          this,
          Invocation.getter(#metrics),
        ),
      ) as _i3.Metrics);

  @override
  _i3.ProtoBook get protoBook => (super.noSuchMethod(
        Invocation.getter(#protoBook),
        returnValue: _FakeProtoBook_14(
          this,
          Invocation.getter(#protoBook),
        ),
      ) as _i3.ProtoBook);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<_i11.AddrInfo> peerInfo(_i2.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #peerInfo,
          [id],
        ),
        returnValue: _i14.Future<_i11.AddrInfo>.value(_FakeAddrInfo_15(
          this,
          Invocation.method(
            #peerInfo,
            [id],
          ),
        )),
      ) as _i14.Future<_i11.AddrInfo>);

  @override
  _i14.Future<List<_i2.PeerId>> peers() => (super.noSuchMethod(
        Invocation.method(
          #peers,
          [],
        ),
        returnValue: _i14.Future<List<_i2.PeerId>>.value(<_i2.PeerId>[]),
      ) as _i14.Future<List<_i2.PeerId>>);

  @override
  _i14.Future<void> removePeer(_i2.PeerId? id) => (super.noSuchMethod(
        Invocation.method(
          #removePeer,
          [id],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<void> addOrUpdatePeer(
    _i2.PeerId? peerId, {
    List<_i13.MultiAddr>? addrs,
    List<String>? protocols,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdatePeer,
          [peerId],
          {
            #addrs: addrs,
            #protocols: protocols,
            #metadata: metadata,
          },
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  _i14.Future<_i20.PeerInfo?> getPeer(_i2.PeerId? peerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeer,
          [peerId],
        ),
        returnValue: _i14.Future<_i20.PeerInfo?>.value(),
      ) as _i14.Future<_i20.PeerInfo?>);
}

/// A class which mocks [EventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventBus extends _i1.Mock implements _i7.EventBus {
  MockEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Subscription<dynamic> subscribe(
    Object? eventType, {
    List<_i7.SubscriptionOpt>? opts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [eventType],
          {#opts: opts},
        ),
        returnValue: _FakeSubscription_16<dynamic>(
          this,
          Invocation.method(
            #subscribe,
            [eventType],
            {#opts: opts},
          ),
        ),
      ) as _i7.Subscription<dynamic>);

  @override
  _i14.Future<_i7.Emitter> emitter(
    dynamic eventType, {
    List<_i7.EmitterOpt>? opts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emitter,
          [eventType],
          {#opts: opts},
        ),
        returnValue: _i14.Future<_i7.Emitter>.value(_FakeEmitter_17(
          this,
          Invocation.method(
            #emitter,
            [eventType],
            {#opts: opts},
          ),
        )),
      ) as _i14.Future<_i7.Emitter>);

  @override
  List<String> getAllEventTypes() => (super.noSuchMethod(
        Invocation.method(
          #getAllEventTypes,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
}

/// A class which mocks [Subscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscription<T> extends _i1.Mock implements _i7.Subscription<T> {
  MockSubscription() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Stream<T> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<T>.empty(),
      ) as _i14.Stream<T>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);
}
